### PR TITLE
[SDPA-2552] Update media library label in wysiwyg

### PR DESCRIPTION
**Pull request by rubyllamadora**
### This updates Media Library label in wysiwyg toolbar

Jira: https://digital-engagement.atlassian.net/browse/SDPA-2552
Related PR: https://github.com/dpc-sdp/tide_core/pull/171  - It's where the CKEditor css overrides

Testing branch: https://nginx-php-content-vic-pr-947.lagoon.vicsdp.amazee.io/

### CODE REVIEW

**Comment by rubyllamadora** [comment]
There is failing issue in build that is unrelated to changes in this PR. Build should pass once develop build passes.

**Comment by anthony-malkoun** [comment]
Hey @rubyllamadora can you reach out to Vincent or Nadim and see why your build is failing?

**Comment by rubyllamadora** [comment]
> Hey @rubyllamadora can you reach out to Vincent or Nadim and see why your build is failing?

Hi @anthony-malkoun, this is now fixed and ready for review when you get a chance (:

**Comment by rubyllamadora** [comment]
@anthony-malkoun @vincent-gao @MdNadimHossain, PR environment is now working if you can review please when chance.

**Review by MdNadimHossain — APPROVED** [review]
Looks fine to me

**Review by vincent-gao — APPROVED** [review]

**Comment by rubyllamadora** [comment]
Closing as they no longer require a rename of the label. Default "Media" stays as is.

**Pull request closed without merging**
